AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  S3BucketName:
    Description: 'The name of your S3 Bucket.'
    Type: String
    Default: 'tru-cloudtrail-bucket'
  S3KeyPrefix:
    Description: 'Specifies the Amazon S3 key prefix that comes after the name of the bucket you have designated for log file delivery.'
    Type: String
    Default: ''
  KMSKeyID:
    Description: 'The ARN of the KMS Key you wish to use.'
    Type: String
    Default: ''
  TrailName:
    Description: 'The name of your newly created CloudTrail trail.'
    Type: String
    Default: 'tru-cloudtrail-trail'
Resources:
  TrailLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub ${S3KeyPrefix}/TruCloudTrailLogs
  TrailLogGroupRole:
     Type: 'AWS::IAM::Role'
     Properties:
       RoleName: !Sub ${S3KeyPrefix}-TruCloudWatchLogsRole
       AssumeRolePolicyDocument:
         Version: '2012-10-17'
         Statement:
         - Sid: CloudTrailAssumeRole
           Effect: Allow
           Principal:
             Service: 'cloudtrail.amazonaws.com'
           Action: 'sts:AssumeRole'
       Policies:
       - PolicyName: 'org-tru-cloudtrail-policy'
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
           - Sid: AWSCloudTrailCreateLogStream
             Effect: Allow
             Action: 'logs:CreateLogStream'
             Resource: !GetAtt 'TrailLogGroup.Arn'
           - Sid: AWSCloudTrailPutLogEvents
             Effect: Allow
             Action: 'logs:PutLogEvents'
             Resource: !GetAtt 'TrailLogGroup.Arn'
  AuditAccountTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: True
      EnableLogFileValidation: True
      IsOrganizationTrail: True
      IsMultiRegionTrail: True
      IncludeGlobalServiceEvents: True
      S3BucketName: !Ref S3BucketName
      S3KeyPrefix: !Ref S3KeyPrefix
      KMSKeyId: !Ref KMSKeyID
      TrailName: !Ref TrailName
      CloudWatchLogsLogGroupArn: !GetAtt TrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt TrailLogGroupRole.Arn